apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cpi-triage-ai-daily-summary
  annotations:
    scenarios.ai.sap.com/name: "CPI-Triage-AI"
    executables.ai.sap.com/name: "Daily summary job"
    artifacts.ai.sap.com/cpidataset.kind: "dataset"
    artifacts.ai.sap.com/cpimodel.kind: "model"
    artifacts.ai.sap.com/summaryout.kind: "dataset"
  labels:
    scenarios.ai.sap.com/id: "cpi-triage-ai"
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    container:
      image: <your-registry>/<repo>:cpi-triage-ai-train
      command: ["python","/app/src/summary_job.py"]
