apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cpi-triage-ai-train
  annotations:
    scenarios.ai.sap.com/name: "CPI-Triage-AI"
    executables.ai.sap.com/name: "Train CPI classifier"
    artifacts.ai.sap.com/cpidataset.kind: "dataset"
    artifacts.ai.sap.com/cpimodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "cpi-triage-ai"
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    container:
      image: <your-registry>/<repo>:cpi-triage-ai-train
      command: ["python","/app/src/train_cpi_btpcore.py"]
